### ISSUE TITLE
Not Optimizing in some instances

### ISSUE THREAD

**Issue by sjghose** [humblerookie/optimized_cached_image#1]
UPDATE: Think I know what's contributing to the issue - only when I specify **width:** it doesn't compress the images. If I specify length: no image is displayed
OptimizedCacheImage(   
             imageUrl: widget.itemzs[index].originalimageurl,
            width:300,
Also in my test example 8 images compress from 24.2 MB to 4.3 MB in memory which is awesome.

In my brief tests for OptimizedCacheImageProvider using your example image (second one) I didn't see a change in memory used. It used 7.3MB with both CachedNetworkImage and OptimizedCacheImageProvider. The example image for OptimizedCacheImage  went down from 2.3MB to 278.2 KB which is terrific
.

Thanks for taking this initiative on - will be quite useful.
I used all three - a) OptimizedCacheImageProvider b) OptimizedCacheImage c) CachedNetworkImage
loading 8 network images - I am not seeing a change in the memory allocations between all three. I used Dart Observatory to compare the heap allocations and uninstalled the app between tests. They stay fairly constant in my case 23.7MB. Is there something that has to be implemented differently to get the optimized image into memory?

**Comment by humblerookie** [comment]
Hey thanks for writing and reporting this. Just a check here are the memory snapshots I've taken of OptimizedNetworkImage vs CachedNetworkImage on my pixel3a for about 20 images

![OptimizedNetworkImage](https://ibb.co/SNBsNMM)
![CachedNetworkImage](https://ibb.co/fCvHhxF)


If you carefully look at the two while the used memory is the same, decode bitmaps are a part of the "external" memory rather than "used" memory. See [this link.](https://flutter.dev/docs/development/tools/devtools/memory). There seems to be a pretty obvious difference in that regard. I've yet to work on proper memory optimizations and a bunch of other stuff on this library.
I'll take a look at the width issue and get back.

**Comment by humblerookie** [comment]
@sjghose  https://github.com/humblerookie/optimized_cached_image/pull/2 Should fix this. There is a new release on pub [0.1.4](https://pub.dev/packages/optimized_cached_image/versions/0.1.4). Do let me know if you're still facing any issue.

**Comment by sjghose** [comment]
That was quick!! Works great. Yes issue is fixed - I am able to specify width. Results of my tests - I took a snapshot of heap memory
#OptimizedNetworkImage (width:300) Images **36 - 8MB**
![image](https://user-images.githubusercontent.com/43908845/77835200-c5399980-7120-11ea-8837-19822cb9cd25.png)

#CachedNetworkImage (width:300)  Images **36 - 17.7MB**
![image](https://user-images.githubusercontent.com/43908845/77835223-ff0aa000-7120-11ea-9ea2-fc0fe7912fb9.png)

I have a separate observation where it appears at first glance the cached images are taking longer to read - that could be a factor of my code or CacheManager - will have to look at that separately. Thanks for your work.

**Comment by humblerookie** [comment]
Hmm, this might need more investigation on my part; could you maybe send me snap of the heap dump at that time?

**Comment by humblerookie** [comment]
@sjghose : I've made a small change that allows streaming/chunked downloads via a config parameter called `useHttpStream`(v0.1.6 check readme for more) which further reduces the memory print check #3  (added screenshot as well).
