### ISSUE TITLE
Support new flutter_cache_manager 2.x

### ISSUE THREAD

**Issue by winterdl** [humblerookie/optimized_cached_image#30]
Thank you for the lib, it's saved me from the crash of loading a lot images, but the lib using flutter_cache_manager 1.x, it's good if have a branch support flutter_cache_manager 2.x, because it's conflict with some packages I used in the app. 

Thank you

**Comment by humblerookie** [comment]
Thanks for reporting this,
I'll take a look and upgrade it.

**Comment by amugofjava** [comment]
I've found the same thing. `optimized_cached_image` has really helped with reducing crashes in my app due to lots of images, but it would be fantastic if its dependencies could be updated.

**Comment by humblerookie** [comment]
@amugofjava I have been trying to upgrade sometime back but deferred since a lot of the code for the `fcm` has changed.
 It seems like the original purpose of this library has been implemented via [this PR](https://github.com/Baseflow/flutter_cache_manager/pull/236). This includes pretty much most of the functionality OIC was built for. I'd recommend migrating to it.
 The only thing missing is probably automatically detecting layout size which should be straightforward i.e. adding a layoutbuilder and supplying[ `maxHeightDiskCache/maxWidthDiskCache`](https://github.com/Baseflow/flutter_cached_network_image/blob/master/lib/src/cached_image_widget.dart#L228) for the `CachedNetworkImage` instance.
 
 ```
 I'll publish a migration guide soon after comparing memory footprint, since the cache manager library uses `image` library (known to have performance issues on android and ios) to compress whereas OIC uses `flutter_image_compress`.

**Comment by humblerookie** [comment]
I was checking this today and it seems the benchmarks are still way off, almost like 9x difference in memory footprint, I feel this might be due to the use of `image` library in `flutter_cache_manager` which is inefficient. I'll update this library for compatibility now.

**Comment by amugofjava** [comment]
Thanks @humblerookie,

I did take a good look at the new Image support in the cache manager, but I you're right here, their choice of image library is not as efficient. What I like about your package is that it's fast and more memory efficient than other packages I have tried.

**Comment by winterdl** [comment]
There flutter_cached_network_image always make my app crashes, maybe the fcm ver 2 uses a lot of memory as you mentioned.

**Comment by humblerookie** [comment]
@winterdl  @amugofjava  I've updated this library to the new FCM, Here's the [pre-release](https://pub.dev/packages/optimized_cached_image/versions/2.0.0-dev.1). If you wish to try it out.

Also the relevant [PR](https://github.com/humblerookie/optimized_cached_image/pull/33)

**Comment by amugofjava** [comment]
Thanks @humblerookie - that's fantastic. Will give the pre-release a try and let you know how it goes.

**Comment by winterdl** [comment]
Thanks @humblerookie, I will try the update and let you know.

**Comment by amugofjava** [comment]
Hi @humblerookie,

I am getting the same error with `_File`. I think it might be an issue with the `file` package that `flutter_cache_manager` uses. The factory method in `io.File` returns a `_File` instance unless another API plugs in and overwrites some or all of the methods:

```
  factory File(String path) {
    final IOOverrides? overrides = IOOverrides.current;
    if (overrides == null) {
      return new _File(path);
    }
    return overrides.createFile(path);
  }
```

The `file` packages provides implementation for the `io.File` methods such as `createFile`. It may be that either via a bug or some missing setup perhaps that the `file` package is not setting up the overrides.

The result is that in `image_transformer.dart` at the end of `_scaleImage` a new `fileInfo` is created. It expects a `File` object but gets a `_File` instead from the default `io.File` factory method.

**Comment by humblerookie** [comment]
@amugofjava @yenyichau Thanks for your feedback, I'll take a look

**Comment by humblerookie** [comment]
>I am getting the same error with _File. I think it might be an issue with the file package that flutter_cache_manager uses. The factory method in io.File returns a _File instance unless ano

@amugofjava, @winterdl  Essentially the flutter_cache_manager uses the file package which has a conflicting name with the dart:io package File. Its silly but dart is shitty when it comes to compile-time safety checks. I'll fix this over the weekend

This issue is fixed via #36 . I've released a new version on pub
2.0.0-dev.2. Do give it a shot and let me know if the issue still persists for you.

**Comment by humblerookie** [comment]
Closing this issue feel free to reopen, in case there is any issue

**Comment by winterdl** [comment]
Thank you, it works, but I have to add dependency overrides for some package: 
Warning: You are using these overridden dependencies:
archive, crypto, ! http_parser 4.0.0, ! path_provider 2.0.1

**Comment by amugofjava** [comment]
Works for me @humblerookie, but I did need to check it out from source in order to update flutter_cache_manager in `pubspec.yaml` to the null safe one - which then worked fine  :)

`
flutter_cache_manager: ^3.0.0-nullsafety.2
`
