### ISSUE TITLE
Max cache size

### ISSUE THREAD

**Issue by Tom3652** [humblerookie/optimized_cached_image#47]
Hello !

This is more a question than a bug report :)
What is the default max cache size and is it possible to modify it please ? 

Regards

**Comment by humblerookie** [comment]
@Tom3652  this is based on number of objects rather than size and is handled in the [dependent Flutter Cache Manager library](https://github.com/Baseflow/flutter_cache_manager/blob/1bd161dbe264edf854d09d20b0fd2ed1b266d232/flutter_cache_manager/lib/src/config/_config_io.dart#L21).

You could perhaps create a class that extended `DefaultImageCacheManager` and provide a custom `Config` instance. Later on perhaps you could create a singleton instance of this cachemanager and supply it to your OIC widget.

**Comment by Tom3652** [comment]
Thanks for the reply i will dig into this !
